Revert "nilfs2: reject devices with insufficient block count"
This reverts commit 84621ebd926f2ddfdcd2a6f4c83b936510e445c7.

Causes compilation errors:
fs/nilfs2/the_nilfs.c: In function ‘nilfs_store_disk_layout’:
fs/nilfs2/the_nilfs.c:454:17: error: implicit declaration of function ‘nilfs_msg’ [-Werror=implicit-function-declaration]
  454 |                 nilfs_msg(nilfs->ns_sb, KERN_ERR,
      |                 ^~~~~~~~~
fs/nilfs2/the_nilfs.c:454:34: error: ‘struct the_nilfs’ has no member named ‘ns_sb’; did you mean ‘ns_sbh’?
  454 |                 nilfs_msg(nilfs->ns_sb, KERN_ERR,
      |                                  ^~~~~
      |                                  ns_sbh
fs/nilfs2/the_nilfs.c:461:43: error: ‘struct the_nilfs’ has no member named ‘ns_sb’; did you mean ‘ns_sbh’?
  461 |         nblocks = (u64)i_size_read(nilfs->ns_sb->s_bdev->bd_inode) >>
      |                                           ^~~~~
      |                                           ns_sbh
fs/nilfs2/the_nilfs.c:462:24: error: ‘struct the_nilfs’ has no member named ‘ns_sb’; did you mean ‘ns_sbh’?
  462 |                 nilfs->ns_sb->s_blocksize_bits;
      |                        ^~~~~
      |                        ns_sbh
fs/nilfs2/the_nilfs.c:472:42: error: ‘struct the_nilfs’ has no member named ‘ns_sb’; did you mean ‘ns_sbh’?
  472 |                         nilfs_msg(nilfs->ns_sb, KERN_ERR,
      |                                          ^~~~~
      |                                          ns_sbh

Signed-off-by: K9100ii <k9100ii.ki@gmail.com>