Revert "UPSTREAM: ipmi: fix use-after-free of user->release_barrier.rda"
This reverts commit 8e824b5db67d0fbc89cecf406a214628953e8f13.

It caused the following compilation error:

drivers/char/ipmi/ipmi_msghandler.c: In function 'free_user':
drivers/char/ipmi/ipmi_msghandler.c:1034:27: error: 'struct ipmi_user' has no member named 'release_barrier'
 1034 |  cleanup_srcu_struct(&user->release_barrier);
      |                           ^~

Not only that, but it's completely incorrect, and the original commit isn't
even applicable.

For the purposes of naming and shaming, I had gotten it from here:
https://github.com/cschsz/android_kernel_samsung_exynos7870/commit/20d3b684a4d563ab51a57fbe652b3d68fcc28f89

Signed-off-by: TALU <taluemail272@gmail.com>